name: Docs --> Wiki Sync
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]

jobs:
  sync_docs:
    name: Sync docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version
        uses: actions/checkout@v3
      - name: Sync with local action
        uses: jaku-jaku/jx-external-repo-sync-action@v1.0.1
        with:
          commit-message: "[Action BOT] Auto-sync Wiki From ./docs"
          source-directory: "./docs"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.JACK_GITHUB_TOKEN }}
